#!/bin/bash

# =================================================================
#      Advanced IPv6 Tunnel Manager (HUB & CLIENT) v4.1
#      Supports 7 Servers + Select by Name + Persistence
# =================================================================

# --- Configuration File Path ---
CONFIG_FILE="/etc/tunnel_config.conf"

# --- Color Codes ---
C_RESET='\033[0m'
C_CYAN='\033[1;36m'
C_GREEN='\033[1;32m'
C_RED='\033[1;31m'
C_YELLOW='\033[1;33m'
C_BLUE='\033[1;34m'
C_MAGENTA='\033[1;35m'

# --- Global Constants (7 Servers) ---
declare -a IPV6_SUBNETS=(
    "fd45:f7a7:539a" 
    "fda5:d72a:4e2f" 
    "fd11:e4fd:f055" 
    "fd76:2917:72d9" 
    "fdce:8ee9:a813"
    "fd79:bf37:1d4d"
    "fd9b:cd62:8f26"
)
declare -a IPV4_SUBNETS=("172.16.1" "172.16.2" "172.16.3" "172.16.4" "172.16.5" "172.16.6" "172.16.7")

# --- Root Check ---
if [ "$(id -u)" -ne 0 ]; then
    echo -e "\n${C_RED}[!] ERROR: This script must be run as root.${C_RESET}"
    exit 1
fi

# --- Helper: Load Config ---
function load_config() {
    if [ -f "$CONFIG_FILE" ]; then
        source "$CONFIG_FILE"
    fi
}

# --- Helper: Save Config (Hub) ---
function save_hub_config() {
    cat <<EOF > "$CONFIG_FILE"
MODE="HUB"
IP_KHAREJ="$IP_KHAREJ"
IFACE_NAME="$IFACE_NAME"
IP_IRAN_1="$IP_IRAN_1"; NAME_IRAN_1="$NAME_IRAN_1"
IP_IRAN_2="$IP_IRAN_2"; NAME_IRAN_2="$NAME_IRAN_2"
IP_IRAN_3="$IP_IRAN_3"; NAME_IRAN_3="$NAME_IRAN_3"
IP_IRAN_4="$IP_IRAN_4"; NAME_IRAN_4="$NAME_IRAN_4"
IP_IRAN_5="$IP_IRAN_5"; NAME_IRAN_5="$NAME_IRAN_5"
IP_IRAN_6="$IP_IRAN_6"; NAME_IRAN_6="$NAME_IRAN_6"
IP_IRAN_7="$IP_IRAN_7"; NAME_IRAN_7="$NAME_IRAN_7"
EOF
}

# --- Helper: Save Config (Client) ---
function save_client_config() {
    cat <<EOF > "$CONFIG_FILE"
MODE="CLIENT"
SERVER_NUM="$SERVER_NUM"
IP_IRAN="$IP_IRAN"
IP_KHAREJ="$IP_KHAREJ"
IFACE_NAME="$IFACE_NAME"
EOF
}

# --- Function: Apply & Persist HUB Configuration ---
function apply_hub() {
    echo -e "\n${C_YELLOW}[*] Generating persistent configuration & applying tunnels...${C_RESET}"
    
    # Start creating /etc/rc.local content
    cat <<EOF > /etc/rc.local
#!/bin/bash
# Auto-generated by Tunnel Manager v4.1 (HUB Mode - 7 Servers)

# 1. Cleanup
for i in {1..7}; do
    ip link del IRAN\${i}_SIT 2>/dev/null
    ip link del IRAN\${i}_GRE 2>/dev/null
done
ip link del sit0 2>/dev/null
ip link del ip6gre0 2>/dev/null

# 2. Firewall
iptables -F; iptables -X; iptables -t nat -F; iptables -t nat -X
iptables -P INPUT ACCEPT; iptables -P OUTPUT ACCEPT; iptables -P FORWARD ACCEPT

# 3. Create Tunnels
EOF

    # Loop to append tunnel config for 7 servers
    for i in {0..6}; do
        s_num=$((i+1))
        
        # Access variables dynamically
        ip_var="IP_IRAN_$s_num"
        current_ip=${!ip_var}
        
        v6_pre=${IPV6_SUBNETS[$i]}
        v4_pre=${IPV4_SUBNETS[$i]}

        cat <<EOF >> /etc/rc.local
# Server $s_num
ip tunnel add IRAN${s_num}_SIT mode sit remote $current_ip local $IP_KHAREJ
ip -6 addr add ${v6_pre}::1/64 dev IRAN${s_num}_SIT
ip link set IRAN${s_num}_SIT mtu 1480 up
ip -6 tunnel add IRAN${s_num}_GRE mode ip6gre remote ${v6_pre}::2 local ${v6_pre}::1
ip addr add ${v4_pre}.1/30 dev IRAN${s_num}_GRE
ip link set IRAN${s_num}_GRE mtu 1436 up

EOF
    done

    # Finish /etc/rc.local
    cat <<EOF >> /etc/rc.local
# 4. Routing
sysctl -w net.ipv4.ip_forward=1 >/dev/null
iptables -t nat -A POSTROUTING -o $IFACE_NAME -j MASQUERADE
netfilter-persistent save >/dev/null 2>&1

exit 0
EOF

    chmod +x /etc/rc.local
    /etc/rc.local
    echo -e "${C_GREEN}[+] Configuration applied and saved successfully for 7 servers.${C_RESET}"
}

# --- Function: Apply & Persist CLIENT Configuration ---
function apply_client() {
    echo -e "\n${C_YELLOW}[*] Generating persistent configuration & applying tunnels...${C_RESET}"
    
    IDX=$((SERVER_NUM - 1))
    V6_PRE=${IPV6_SUBNETS[$IDX]}
    V4_PRE=${IPV4_SUBNETS[$IDX]}

    cat <<EOF > /etc/rc.local
#!/bin/bash
# Auto-generated by Tunnel Manager v4.1 (CLIENT Mode)

# 1. Cleanup
ip link del KHAREJ_SIT 2>/dev/null
ip link del KHAREJ_GRE 2>/dev/null
ip link del sit0 2>/dev/null
ip link del ip6gre0 2>/dev/null

# 2. Firewall
iptables -F; iptables -X; iptables -t nat -F; iptables -t nat -X
iptables -P INPUT ACCEPT; iptables -P OUTPUT ACCEPT; iptables -P FORWARD ACCEPT

# 3. Create Tunnel (Client #$SERVER_NUM)
ip tunnel add KHAREJ_SIT mode sit remote $IP_KHAREJ local $IP_IRAN
ip -6 addr add ${V6_PRE}::2/64 dev KHAREJ_SIT
ip link set KHAREJ_SIT mtu 1480 up

ip -6 tunnel add KHAREJ_GRE mode ip6gre remote ${V6_PRE}::1 local ${V6_PRE}::2
ip addr add ${V4_PRE}.2/30 dev KHAREJ_GRE
ip link set KHAREJ_GRE mtu 1436 up

# 4. Routing
sysctl -w net.ipv4.ip_forward=1 >/dev/null
iptables -t nat -A POSTROUTING -o $IFACE_NAME -j MASQUERADE
netfilter-persistent save >/dev/null 2>&1

exit 0
EOF

    chmod +x /etc/rc.local
    /etc/rc.local
    echo -e "${C_GREEN}[+] Configuration applied and saved successfully.${C_RESET}"
}

# --- Setup HUB Wizard ---
function setup_hub_wizard() {
    clear
    echo -e "${C_CYAN}=== HUB Server (Kharej) Initial Setup ===${C_RESET}\n"
    
    load_config
    [ -z "$IP_KHAREJ" ] && IP_KHAREJ="0.0.0.0"
    [ -z "$IFACE_NAME" ] && IFACE_NAME="eth0"

    read -p ">> HUB Public IP [$IP_KHAREJ]: " input_ip
    IP_KHAREJ=${input_ip:-$IP_KHAREJ}
    
    read -p ">> Interface Name [$IFACE_NAME]: " input_iface
    IFACE_NAME=${input_iface:-$IFACE_NAME}

    echo ""
    for i in {1..7}; do
        ip_var="IP_IRAN_$i"
        name_var="NAME_IRAN_$i"
        
        current_ip=${!ip_var}
        current_name=${!name_var}
        [ -z "$current_name" ] && current_name="Client-$i"
        [ -z "$current_ip" ] && current_ip="0.0.0.0"

        echo -e "${C_BLUE}--- Client #$i Setup ---${C_RESET}"
        read -p "   Name [$current_name]: " input_name
        read -p "   IP   [$current_ip]: " input_client_ip
        
        declare "NAME_IRAN_$i=${input_name:-$current_name}"
        declare "IP_IRAN_$i=${input_client_ip:-$current_ip}"
    done

    save_hub_config
    apply_hub
    read -p "Press Enter to return to menu..."
}

# --- Edit HUB Wizard (Updated) ---
function edit_hub_wizard() {
    load_config
    if [ "$MODE" != "HUB" ]; then
        echo -e "${C_RED}[!] Config file is not set to HUB mode. Run Setup first.${C_RESET}"
        read -p "Press Enter..."
        return
    fi

    while true; do
        clear
        echo -e "${C_CYAN}=== Edit HUB Tunnels (7 Servers) ===${C_RESET}"
        echo -e "HUB IP: ${C_GREEN}$IP_KHAREJ${C_RESET} | Interface: ${C_GREEN}$IFACE_NAME${C_RESET}\n"
        
        echo -e "   ID | Name                 | IP Address"
        echo -e "   ---+----------------------+----------------"
        for i in {1..7}; do
            ip_val="IP_IRAN_$i"
            name_val="NAME_IRAN_$i"
            printf "   $i  | ${C_YELLOW}%-20s${C_RESET} | %s\n" "${!name_val}" "${!ip_val}"
        done
        echo ""
        echo -e "   [8] Edit HUB IP / Interface"
        echo -e "   [0] Back / Apply Changes"
        
        echo ""
        read -p ">> Type Server NAME (or ID) to edit: " user_input
        
        # Handle special menu options
        if [ "$user_input" == "0" ]; then
            save_hub_config
            apply_hub
            break
        elif [ "$user_input" == "8" ]; then
            read -p ">> New HUB IP [$IP_KHAREJ]: " inp
            IP_KHAREJ=${inp:-$IP_KHAREJ}
            read -p ">> New Interface [$IFACE_NAME]: " inf
            IFACE_NAME=${inf:-$IFACE_NAME}
            continue
        fi

        # Logic to find ID by Name OR ID
        TARGET_ID=""
        
        # 1. Check if input is a valid number 1-7
        if [[ "$user_input" =~ ^[1-7]$ ]]; then
            TARGET_ID=$user_input
        else
            # 2. Search for the Name in variables
            for i in {1..7}; do
                name_var="NAME_IRAN_$i"
                # Check for exact match
                if [ "${!name_var}" == "$user_input" ]; then
                    TARGET_ID=$i
                    break
                fi
            done
        fi

        # If found, proceed to edit
        if [ -n "$TARGET_ID" ]; then
            n_var="NAME_IRAN_$TARGET_ID"
            i_var="IP_IRAN_$TARGET_ID"
            
            echo -e "\n${C_GREEN}>> Editing Server #$TARGET_ID (${!n_var})${C_RESET}"
            read -p "   New Name [${!n_var}]: " nn
            read -p "   New IP   [${!i_var}]: " ni
            
            declare "NAME_IRAN_$TARGET_ID=${nn:-${!n_var}}"
            declare "IP_IRAN_$TARGET_ID=${ni:-${!i_var}}"
        else
            echo -e "\n${C_RED}[!] Server '$user_input' not found.${C_RESET}"
            sleep 1.5
        fi
    done
}

# --- Setup CLIENT Wizard ---
function setup_client_wizard() {
    clear
    echo -e "${C_CYAN}=== CLIENT Server (Iran) Setup ===${C_RESET}\n"
    
    load_config
    [ -z "$SERVER_NUM" ] && SERVER_NUM="1"
    [ -z "$IP_IRAN" ] && IP_IRAN="0.0.0.0"
    [ -z "$IP_KHAREJ" ] && IP_KHAREJ="0.0.0.0"
    [ -z "$IFACE_NAME" ] && IFACE_NAME="ens160"

    read -p ">> Client Number (1-7) [$SERVER_NUM]: " sn
    SERVER_NUM=${sn:-$SERVER_NUM}
    
    if ! [[ "$SERVER_NUM" =~ ^[1-7]$ ]]; then
         echo -e "\n${C_RED}[!] FATAL: Invalid selection. Must be 1-7.${C_RESET}"
         read -p "Press Enter..."
         return
    fi
    
    read -p ">> This Server Public IP [$IP_IRAN]: " ii
    IP_IRAN=${ii:-$IP_IRAN}

    read -p ">> HUB (Kharej) Public IP [$IP_KHAREJ]: " ik
    IP_KHAREJ=${ik:-$IP_KHAREJ}

    read -p ">> Interface Name [$IFACE_NAME]: " inf
    IFACE_NAME=${inf:-$IFACE_NAME}

    save_client_config
    apply_client
    read -p "Press Enter to return to menu..."
}

# --- Wipe ---
function wipe_all() {
    echo -e "\n${C_RED}[!] WARNING: This will delete config files and tunnels.${C_RESET}"
    read -p "Are you sure? (y/n): " c
    if [ "$c" == "y" ]; then
        rm "$CONFIG_FILE" 2>/dev/null
        echo "#!/bin/bash" > /etc/rc.local
        echo "exit 0" >> /etc/rc.local
        chmod +x /etc/rc.local
        
        # Cleanup
        for i in {1..7}; do ip link del IRAN${i}_SIT 2>/dev/null; done
        ip link del KHAREJ_SIT 2>/dev/null
        ip link del sit0 2>/dev/null
        ip link del ip6gre0 2>/dev/null
        
        echo -e "${C_GREEN}System Wiped.${C_RESET}"
        sleep 2
    fi
}

# --- Main Menu ---
while true; do
    clear
    echo -e "${C_CYAN}==============================================${C_RESET}"
    echo -e "${C_CYAN}    Advanced Tunnel Manager v4.1 (7 Servers)  ${C_RESET}"
    echo -e "${C_CYAN}==============================================${C_RESET}"
    echo ""
    echo -e "   ${C_GREEN}[1]${C_RESET} Setup HUB Server (Kharej) - First Time"
    echo -e "   ${C_GREEN}[2]${C_RESET} Edit HUB Configuration (Select by NAME/ID)"
    echo -e "   ---------------------------------------"
    echo -e "   ${C_BLUE}[3]${C_RESET} Setup/Edit CLIENT Server (Iran)"
    echo -e "   ---------------------------------------"
    echo -e "   ${C_RED}[4]${C_RESET} Uninstall & Wipe Everything"
    echo -e "   ${C_YELLOW}[0]${C_RESET} Exit"
    echo ""
    read -p ">> Select Option: " opt

    case $opt in
        1) setup_hub_wizard ;;
        2) edit_hub_wizard ;;
        3) setup_client_wizard ;;
        4) wipe_all ;;
        0) exit 0 ;;
        *) echo "Invalid option"; sleep 1 ;;
    esac
done
